# prod is oe
# dev is personal
version: 2
jobs:
  ecr_push:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker
      - run:
          name: "Export Environment vars"
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
                AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
                AWS_ACCOUNT_ID=${PROD_AWS_ACCOUNT_ID}
            else
                AWS_ACCESS_KEY_ID=${DEV_AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY=${DEV_AWS_SECRET_ACCESS_KEY}
                AWS_ACCOUNT_ID=${DEV_AWS_ACCOUNT_ID}
            fi

            echo 'export CIRCLE_SHA1_SHORT=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV
            echo 'export BASE_ECR_US_EAST_1_URI=$(echo ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com)' >> $BASH_ENV
            source $BASH_ENV

            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

            eval $(aws ecr get-login --no-include-email --region us-east-1)
            docker build -t ${BASE_ECR_US_EAST_1_URI}/circleci-test:${CIRCLE_SHA1_SHORT} https://github.com/docker-library/hello-world.git#master:amd64/hello-world
            docker tag ${BASE_ECR_US_EAST_1_URI}/circleci-test:${CIRCLE_SHA1_SHORT} ${BASE_ECR_US_EAST_1_URI}/circleci-test:latest
            docker push ${BASE_ECR_US_EAST_1_URI}/circleci-test:${CIRCLE_SHA1_SHORT}
            docker push ${BASE_ECR_US_EAST_1_URI}/circleci-test:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - ecr_push